### ISSUE TITLE
Add instructions to run script on Windows

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/ocr-convert-image-to-text#12]
[Usage section](https://github.com/prabhakar267/ocr-convert-image-to-text/blob/master/README.md#usage) in Readme mentions the instruction to run the script on Linux, but it should be more generic to support Windows as well.

**Comment by wishx97** [comment]
Hi, I would like to solve this.
Should I create a window version main.py or just update Usage Section in Readme?

**Comment by prabhakar267** [comment]
Script file should remain same
You can update the [usage](https://github.com/prabhakar267/ocr-convert-image-to-text/blob/master/README.md#usage) section in README
