### ISSUE TITLE
Add instructions to run script on MacOS

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/ocr-convert-image-to-text#13]
[Usage section](https://github.com/prabhakar267/ocr-convert-image-to-text/blob/master/README.md#usage) in Readme mentions the instruction to run the script on Linux, but it should be more generic to support MacOS as well.

**Comment by meghanasudhi** [comment]
I ran it on  MacOS.

I would run it as 

python3 main.py "Input_directory"

Input Directory would be the path of the directory.


The folder converted_text would be in the same input directory.

**Comment by prabhakar267** [comment]
Verified on Mac
Works fine
