### ISSUE TITLE
Add requirements.txt and instructions to setup a virtual environment

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/ocr-convert-image-to-text#15]
After merging #14 some dependencies are to be present before this would work, so adding a ```requirements.txt``` and instructions to setup virtual environment would be handy.
([reference instructions](https://github.com/prabhakar267/vertikin/blob/master/server/README.md#setup))

**Comment by suresttexas00** [comment]
Hello;
 argparse is part of the standard library.

If you run these steps (instructions):

1) create the virtual environment:
`virtualenv venv --no-site-packages`

2) Activate the environment:
`source venv/bin/activate`

3) Run pip freeze to get the installed packages (should be none):
`pip freeze >requirements.txt`

You will find one blank line.
To test this really works, from the venv:
`pip install requests`

Now run pip freeze and you will see that requirements.txt contains something like:
```
certifi==2018.1.18
chardet==3.0.4
idna==2.6
requests==2.18.4
urllib3==1.22
```

However, your main.py runs fine in the venv with no additional dependencies!

**Comment by prabhakar267** [comment]
@suresttexas00 I know how to do it, but it's open for someone else to contribute, feel free to open a PR for adding the same 😄

**Comment by suresttexas00** [comment]
My point is nothing is needed... You have no non-standard imports.  Anyone can google any number of very good tutorials on using virtual environments (you have "two issues" in this "issue").

**Comment by prabhakar267** [comment]
@suresttexas00 makes sense
