### ISSUE TITLE
ValueError when running example

### ISSUE THREAD

**Issue by ctilly** [prabhakar267/ocr-convert-image-to-text#2]
I'm simply attempting to run the example and I get a ValueError in one of the PIL modules.  Any ideas what is going on?

C:\Projects\OCR\ocr-convert-image-to-text-master>python main.py C:\Projects\OCR
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from pytesser.pytesser import *
  File "C:\Projects\OCR\ocr-convert-image-to-text-master\pytesser\pytesser.py", line 6, in <module>
    import Image
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 27, in <module>
    from . import VERSION, PILLOW_VERSION, _plugins
ValueError: Attempted relative import in non-package

**Comment by prabhakar267** [comment]
@ctilly 
I have made some changes in commit d476fc60da9a1305bf5b2ffc398c9e99d593aecf 
That should solve your issue as well, kindly refer to the same. If you face any problem after updating as well, feel free to reopen this issue or open a new one.
