### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/ocr-convert-image-to-text#21]
Add unit tests for the script

**Comment by ghost** [comment]
I would like to work on this using python unittest framework.
Do you have any specific test cases?

**Comment by prabhakar267** [comment]
Just the general test cases relevant to the script

**Comment by modelmat** [comment]
*probably should have mentioned I've been working on this :stuck_out_tongue:*

**Comment by ghost** [comment]
I will try with mock objects.
