### ISSUE TITLE
whats the command to process a single image instead of a directory (MacOSX)

### ISSUE THREAD

**Issue by pranavrajt** [prabhakar267/ocr-convert-image-to-text#36]
I am trying to run this on one single file, but it returns a blank output .txt file. 
I used the command "python main.py --input_file sample/test.jpg"

Am i missing something here?

**Comment by tinkupa1991** [comment]
The code is developed to work on directories as the first line of code execution asks for input and/or output directory. Kindly input input directory or modify the main.py to suit to your case.

**Comment by prabhakar267** [comment]
I think there was something added to support one file. I look into it today. 
Thanks for reporting @pranavrajt

**Comment by prabhakar267** [comment]
Looks like this is fixed now.
@pranavrajt Feel free to reopen if not fixed
