### ISSUE TITLE
Add command to print output to console

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/ocr-convert-image-to-text#38]
Currently there is only one way of printing the output, which is in a text file. Add an option to print the output to console if no output file is provided.

**Comment by AlexandreDewilde** [comment]
I'm interested, I can do it but how it should be implemented? print output only when there is no output file provided or/and add a new argument (for instance: --print-console)?

**Comment by prabhakar267** [comment]
There is an [`output_dir`](https://github.com/prabhakar267/ocr-convert-image-to-text/blob/master/main.py#L151) flag in arguments, if that flag is missing print to console

**Comment by allEyezOnCode** [comment]
and have I to rewrite tests?
