### ISSUE TITLE
trackback No file or Directory Error not resolved 

### ISSUE THREAD

**Issue by pcakhilnadh** [prabhakar267/ocr-convert-image-to-text#4]
![screen shot 2017-09-14 at 9 37 34 am](https://user-images.githubusercontent.com/3054812/30411763-c4983718-9930-11e7-886a-450f15abd3a2.png)

$python main.py sample 
[ after deleting the image in  converted text folder ]

OSError No file or Directory

**Comment by prabhakar267** [comment]
Hi @pcakhilnadh 
Seems like you don't have ```tesseract``` on your system. You can resolve this by installing ```tesseract-ocr``` 
If you are using Ubuntu, you can do;
```
sudo apt-get install tesseract-ocr
```

Reference: https://stackoverflow.com/q/28741563/

**Comment by pcakhilnadh** [comment]
@prabhakar267  Thanks 👍 

For mac user 

$ brew install tesseract

will fix this issue
