### ISSUE TITLE
How to use this tool with other language?

### ISSUE THREAD

**Issue by Cabbagehust2507** [prabhakar267/ocr-convert-image-to-text#46]
I wanna use this tool for Vietnamese language but I cannot find where to set up this. I hope you will reply me soon. Thanks.

**Comment by mhrihab** [comment]
me too can you please answer us

**Comment by ayam04** [comment]
Tesseract supports multiple languages, but by default, it comes with English language data. If you want to recognize text in other languages, you need to download the corresponding language data files. You can find the language data files on the Tesseract GitHub repository or use the tesseract-ocr GitHub organization's tessdata repository.

**Comment by mannan291** [comment]
There is a paid solution on rapidapi, which works for me. It gives 10 free tries https://rapidapi.com/hakimiachraf841/api/ocr-image-to-text4

**Comment by prabhakar267** [comment]
Answer by @ayam04 solves this. Feel free to reopen if more discussion is needed
