### ISSUE TITLE
Provide more informative error if "tesseract-ocr" is missing

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/ocr-convert-image-to-text#5]
If the "tesseract-ocr" is missing on a user's system, the error user gets is:
```
OSError: [Errno 2] No such file or directory
```

which is not very descriptive, we should give a more informative error 
**`tesseract-ocr` missing, use `sudo apt-get install tesseract-ocr` to resolve**

Refer to #4

**Comment by chaintng** [comment]
fix kub https://github.com/prabhakar267/ocr-convert-image-to-text/pull/6
